### ISSUE TITLE
Mojave woes

### ISSUE THREAD

**Issue by bland328** [phreakocious/FractalClock#1]
I love this screensaver, but sadly, it seems not to work under Mojave.

I've only tried it on one system at this point.

**Comment by bland328** [comment]
Oh...and I tried to rebuild it, just in case that cured something, but....it uses OpenGL. Sigh.

**Comment by phreakocious** [comment]
Oddly enough, I have been poking at this a bit recently.  As you discovered, Apple is officially nuking OpenGL in favor of their "Metal" framework starting with Mojave.  The task of porting the code doesn't look too crazy, but still not sure if it will get done...

**Comment by bland328** [comment]
Thanks for responding! It makes me happy that someone is even considering adapting it to Metal, as it is beyond my pay grade at the moment ;)

**Comment by slavanossar** [comment]
Just noticed Quartz screensavers seem to be working again since updating to 10.14.5 🤙

So happy to have it back – I had fractal clock withdrawals a month in and ended up [partially recreating it in JS](https://codepen.io/slavanossar/pen/RezLEa?editors=0010) as a way to learn canvas.

**Comment by bland328** [comment]
Thanks for the update! It's working for me, too.

And nice work on the JS version!

**Comment by phreakocious** [comment]
This is awesome news.  Thanks for posting it here, folks!  Going to mark this as closed.
